import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Scanner;

public class genoma_adv_1 {
    public static void main(String[] args) {
        String genoma = "AAACTAACGGCTCACCGTCTGGGATAGGAGCTTGTCGGGTCCGGAAATCCGTCGATAGTGGTTCGGTGACCTTCGATAGCCGCAGCTTCTTTTGTGTCCCTATGAGAGACATTCGAGTGCGGATTTAGAATCTTCCATTCCCGCTATGGGCCGCCTCTGGTCGCCAGATGCGATGTCCCAACACACTTAGGAAGTTGTGAAGAGTAGGAGTTCTCGCTTGGAACTGGACTGCCTCTGCGGGCTCAGTTGATCCCCGGTAGTTGGTAATATCCAATTTCTGAATGAGAAATTTCGGGGTACCTGGCGGATTAATCATCTCCAGCCGTTGAACCACGGCCACAGGCGGAGGCTTTATAGCATCGAGACTTCTACTACTATTCGTGGACAACAGCTATTTCATTAAAAAGCATCCAAAAGTTCGCAAGTTATCCCATATCGTTACACAACTACCCTAGGGCAACAACCAATACCGGTAAGGGAACATTAGTTGGCCCCCGGTTGTGAAAACATGCAATTCACAGCGCGGTGGTGTGAGTCGAAACAGTCAATAGAGGATGTCAGTAATTAGTATTAAACCTTTCAACCTGAAAATCCAGCTAAGTCAGCCAAATCTGTCTGAAAGAATAAGCCCTTAGCCCACCCTATATCTCCCATTTTTTATATCGCTTGAACTCTTGGGCCGTCCGACCTCGACGCCAAATCATATTGAGTCCTGTGCGAACAGACCGGATTTGACAAAGGTGAGCGGACCATGCGCAGGACCACGTCTCGGGTTTACCTAAGTTTTTCACTGTCCCTCAAGAGTGTAAAGCAATCAGACCAGAGGCGGAAGACGGAACTCTATAACCTCATATCTCTTTGTAGGAACCCACCGGCCATTCAACCTATAGTAACGAAACATTAAATACTTATGGAGCGCCTTCTCGAGTGCAAGGGAATATAGACTGTCTAAGTGTCATACAAGAGATATATATACGAACGGCGTTATTCGAGCTGCTCCGTTATCGATTACGCGCAGAGGCTAGTGAGCATAAATGCCCATCAATCTAGCAGACAGCCTATCGCCTATGCAATCTAAGTGTCGTGGTTGTCAGGTACGCGAAACTAGTACTTGCATACATTTTCTCTGTGCACATCCCGTCGGTTGATACTGTTTCTTGTTCGGTCCCATACTATCTGGCTATTTTACCGCCTTACAGGGACTGCGCTGCTATTTACATTGTCCGTGGGGCACGTACCTACGAGGTGGCGGTTGGATTAATCCGATTGCATCCGCCGAACCGATAAGTGGCCACAATTTAAGGCGAGTGCTCTGTAACAGGCGCACATTCGGCAAGGATGGTGTCACCATGTCCGACCGGCTCGGTTAAGTTCGTATCTTGATCCCATTGGTTACGGCAGCCGCTGCAGGTAAACTGCAGAACCTTATAACCCTCGTGTCGATGAGGTTGATACCAGTTTGTCACAGCGGGGACCCCATTTCAGTTGCTATGCTCGTACCCATCCTTAAACTAGATCGCGGGACTGTTCTGGGAGCGGCACATGGGTAGGCACTCTAGGTATACTATACCAACGCATCGTAATCTAGTCTACGGGATTACATCTCTATCATGAGTAAAGTTTTTCGCCTATTAATGTACGCTGCCGCAAGCGGCGGTCAATTGTTAGCTTCGTTTCCCACTTCGACTTCTGAACTTCATACAGGCACGGAACACCGAGCAGGCCACGGTGTGACCATCTATGGCAGATGGGCAAGCCTGAGTCGTGGGCCTTTTAAGCGGAAGGCCGCAGCATAGGGGCTGCAGTCGGGGGGAGTCCCACTAAACAAACCTCAGCAAATGTATGAAACGCTGGAGTGCTTGTTACGGATACTACGCGTACCTTTCGTCGAACCTCGAAACGGCCAGCCGGGTGTATCTTTGATGGTTTTGTGGGAGCTATAACAGGGTCAGTTCTGCGGCTAGTGTGAACTCGGCATCCAACTTCAGCCAGAGTTACCAAGGATGCAAGATATGTCGCAAGTTCGCGATAGCCAATTGTAGCTAAATGAGTAGTGTCGAATTGAAAATTGAAAGGATGGTCTACCACAGAATACCCTTGTTGATTCAAGGATCAGGTTAGGGAGAGCCTTCTTTGTTCACTCGTTAGTATTGCCAACACACCCAATAGGTCCATCTGACCACGCCACGTTCCACACGCAAACATTCCCTGATATCCGTATTTTCGGCAAATCCTTAAAGACGCCCCAACTTCACGCGGGTCATACCCGTATTCTAACGAGCTTTAACGTGCTCACTCCTCTGTTTTGCAGCGGTTGCCGACTTCACACTACAGTCACTACAAACGTACTATAAATGACCGACCAATCAGTCAACGAACACACCACCTTCCTTCCACAACACTAGTCATAGCAGGACAGCTTTTGTATGCGAGGTATCCTAGAGAGGTCCGAGTCAGGAGGCGTCTTAGTTTTCCATGTCAAATCTTCTTCCCCTTGTTATTTTATGCTTGCGTACGCTAACCTCGCCCCCCTCTTTGATACGATCAGATTGCCGGATGAAACGCCTTCAAAGCCAACATTCAAGTTTCGGGAGGCTAGGTGATGCTTAAGCCTAACCGTGGGCTAAAAGACATTTTACTGATAATTGCACGGCAAACGGACTCTCCTAAGTTTGCACTCTTCTAAAATTGTCTACAGACCACGAGACCATGCGGACAGCATGTCTACCCACGGTACAGTAGTTCGGGCACACGACACGCTCTATTCTACACTGGGTTCTAATATTGCTGCGGAACCAGCCACAGCTCACTAAGGAGAACCGTTCCGTGTTGGCATCGGCCCGTCAACGACCGGACTCTATAGGAGCTTCCAGCCGGCTAGTGACCAACTGGGTCGAAGGGCCAATGGGAGGTCCGTATAACTCAAATGTTACTCACGCCGGCGAGCCCGGTGTGAATCGGGACAGCACGGCGCTCAACATTACCGCTATGATCCCAGCTATAATACGCCATCATCATATAGGGCTGCCTATGGGACCAAAACCGACACGGACCTGAGTGCAACTTTTCCAGGGCAGTGTAGCTTTCTTGCCCTTCATAAGGCCTTAAGACAGGCATAGACAGACAGATCGAGAAGGTATTCTCTGCTAGGAAGCCATCAGTGCTCAGCTAAGGCATTGCAAAAACCTCGAGACTGCTATTCTCGTGAAAGTACTTTCAGCTGTCCTTTTATTCCTATTCGTAGTATTGCCGTTGTGGGGCCAAGTCTCCTTTAAAAACGGGTGGATGTGAGCTTGTCTGATAACAGATTAGAGATTCTCGAGAGTACGCATCGCTACCGCGGTGTCGCATACAACTGGAAGGAACTGGTGAGACAACGGCTACCGATGACTGGTACTAACCAACGTCCCCGAGTTCCGGCACCAAACAACCGAGATTTCCAATTTGAGCAACTTCGCATACCTGCATGAACTAGACCACCTGCCCCATTATCCTAAGCATCTGATTAATAGTGGCCCCTGGTTCAGTGTTCAGGTTCGAGAGCCCCTGCAGAATGCGAAGCATCGAGCGGACAAACGTTCTCAACAGTGTTATCGCGTCATTAACGCTCACGATCGGGCACGGGCGCTTCTAGACGGCTTTATGTTTGAAGTAGCCAATTTCTGTGCGCTTGTGGTCCATCCCTTAGTCTGAGCAGACAGGCCGTCGAACCATAAACCCTAGGCAGTTGAGCGGCGCCCCCGCATACGTCTAGGACCAAGTATGTACACAAGTAGCGGATGACGGTCCGCCGCTAATATTGAGATTCGCTGTTCAAAGTTAATTACATAGGCGAGACGTATTGTTGCTACAGTCGAGCGGGCTTCCGACAAGGGAGACACAATGTTCTCTATAAAATTGTCTACATGCGCGCCAGTATGCCGCGTCGGACCTGACCGAATGACCTGAAGGGATCATGGAGAAACTGGCGGAAGTGTGTAATCGTCACCAGATCTACAAGGGGGCCTAGATCATGCGAACCTAAGACGAGGATTGTTACATCTTCAATCCTTCACGCCGTTTTCGCTGATCGAAAATCATTCGGTCCTCCGATCTCGTTCTATCGTTCCATAGGAACGTTTTCGATTACCATTGAGCGGGCAGTCTCGTTGACGACGTCCGTAGAAAAGCCTTCCCGCGGATCGATCGAGATCTTACTAACCGACCAAACTTCCCCGCCCCCACTGGAGTTGGGCAACCCAAGAAGGTAGGTACCACCTAGTACTTAGATTGCTTTCGCGACTGGACTCCTGCAGATCTACCACCGACCACACGGTCCCTTTGTATTCCTTAAAGTCCAAGCAAGAATCGAGCGCCCGGTGCTATAAAGTGAGAACATAGGGGTTGCTTGTCCTGGGTCCACTCGATGATTAAGCAAGGAACTCCAAGTATTGAGAACGCAAATTAAAACTTCTTCGTCGGCGCTCGGTAGGTCATGCCTCTGAATGTCAGAGTTCGCAGCAGTATCAAGGCCGTGTAGCGTGATGGCGGCAGTTGGCGTTAGCCATTGGGATGGTAATCTCACTCTAGACGAACCTGATTACATATGGGATTTCGGTTACACACCTGGGAGGCTTGTGTGCGACGCGCGAAAGCCCCACAAACGAGTAAACCTAAGAGAACCTAGCATATGACAGCGACGGCTTTAAGAATTTGAAGGTGTTAATGCCGCTCCGGTTTACGTTTGGTCCGCGCAGTGGCGCCGCACCGAATGCCGATACTGAAGTCACAGAATCTTGAGTCCATCCATGGAGGCTAGGATAGTAGAATCTCACAGTCAACGCAGCCAAACTCTTTACAGTTTGCCCATAGCACCGAGACTCATATTGTGTAGCAGGCTAATTCCAATGACGAGCAAAGGGATCAGACTGTAGGATGCTTAAGGGTCATCCCCTATCCTGCTCTGCGTTGCGGCGCCCGCTCATGTTGAGTCTGGGTTCCTGAATCAACGTTGGTTCCCTAGGACTTCTGCCACTAATAGTGTACACCGTCGGAGATGGTGCGGTTTTGGGGGGCTAGAGCTATACCCGAACCGTCAAAGATTCTCAGTGTTATCTGGCGAAAAAGTCGTGCAGTTACGCCCCGGCGTAACGGGGTGATATTAGAACAGACAGCCAGTGGAGCTAGCGTCAACTTCGGGGCGGACCGTACCGAACCTAACATCCTGGTGTATTTCCTGATTGTTTGGAGGTAGCGCTCTATCGTTCACGCCCCTACAAACATACGCATGGAGATCTCATCGGAGCTGTGCCCCTACGGAACAGCGACCGCGCGGTGCAATCTTACCTACCCGCGCAGTATTGCGCACCAAACTGCAACGCCCGTAAATATTTTGGAACCCGCGTCGACCGTGCGGACGTGAGCATTACGAGAGTAGGCCGGGCATGTGACTGTTTTTTGACCATAACAGGCCGGCTGACTACATCCACCTTGAACGCCTATCTTTTACATCAGATTATGTGAGACGCCAATGTGCCTGGTTCCCGTACGTGCGGAACCGGCTCCGTTGAAAACACTTGAGGCCTGCACTTCCCAAAATTATTTAGCAGAGGGCAGTAATTCCCTTGGCGTGTGGTGCCTCGAGTCATAGATAACTGCACTCAACGGACGTCGCAGGCCGGTACAGCCATAATCCGCCATGACCGGGACGTTTTTACGCCTCAGGTGCTCAACGTGCAACGCCCGTGTTGGCCACTGGGAACCTGTTAAGGTCCGGTTGGGTTTCTCCCCCCGATTGTGGGGAATTGTGGCCGTTGCTATCCAATGCTAGTTGCGACCGAGTTACGCCTGGATTACATCCGATGTCCCAAGCCTGTTCGGTCCATAGGACTAGCGACCTTCCTAAGAAGCCACAGTGATGGCGATTATAAAGTTGCCTTGCTTCCTCGTTAATGATCGGTGAGTAAGGATCGCCAAAGTCACCTCTGTACATCAATTTCTTCGCGTAAGCGGCGGATCCCTAGGCTGTGCACGTACGTTAACGATGCCCTATGGCGCACTCTAGGCCCATGTTTACGTACCTGAGCTGAAACCACCTGACTGCTTCAGTCATATACCAGTCCCTCGACTAGCTTGCTGCTGCGACCGCTATGATGACCGTAATTGCCTCCAATACGAGCTAGTGCACGACGGCTGTAAATTAGGGTCAAGGATGGTCACTGAGTGTTGATGCTAAATAACATCACAACGTGATATATTCGGATAAGCGTATACTAAGGCGGTAGTTCGGGCTGGTTTTGGTCCATGTACCTGTACCACAAGCCTTCAACAGGTTTTCTCATTGTTCACATGTAACGTCCATTTCAGTTGAGCTGAGATCGAGTTGCGTGCTATCCTACAGCGAGGCCTTCAGCCTCAGGCTGCTTTACCACCGTGAACTTTGTTACATGGTGATGTGACGAGGATCGCGCTGAGAGTTTCGGGCGACCGCACAGTATAGAGATGGGGGTGAGTCCTAAACCCAACGAGTCGCTCATCTCTATTTTCCCAGCAGAGAGGGCAACGTTAACGCTGACATGTTTGTCGCCCTCATGAAGGCCTCAATGATGATAGAGTCCGTGGGACAGTAGATTAACTTACTGGAAGTTAAAGTCGCTCCGCGAATCTTGGAATCCTCGGGGCACAATATACATGCTGGCCCGTTTAGGATGTTTATACTTTGGGCCGGCACTCAGACCGGTAACCATAAGAATGTTACGAATCCCGGAGTCATGTAATGGGCTCCTAAGCTTAACAGCTTGTTGGGCAGTTAGGTGGCCTTAGGACAAGGAACATTGATGGGCGTCAATGGCGTTCCGCGTAAAAGGATAGGCGTTGTAACTTAGGCGGAAACTCGCACCTCGGTCCATTTGTGGACGCTAAGTCGCATAACAAGTGAGGCAGCTTTGCGGCGTTCCAATCAATACTCCGTTGTACGCAAGAAGCGCTACAGTAAGCAGATCATCGCTCATTGACACTCAACAGAATAGTTGCTTGAATCCGTCCAGATTGACTCCCGGCATAACCCAGGCGAAATACCGAGAATCCGCGGGTAGAGCATCGAGTTTCTCTGCTCGACCCGCCCATAATACGTTACTAGTACTTGCGGCTCCAGTCCGCCCATAAATAATCAGGATATCTTTTCTAGATTGGAGGCTCTCGCCCACTTCTTGGTTGGCGACGATTTGTACCCTGTACTACAATTCAGGGCCGCAAGAATATCAAGGGTACCTATTCACGAGTTTACAGCATCGATTGACGTAGGCTGTTATAAATCATGACAAAGACGGCTAGGCTTAACCGCCTGCTGCTCGCTGGCTCCTGGGGACCCGTCTATAGTGATGTTTATTCGAGACACCTGACTGACTGGAACTAAGACATACCATCTAGGGCCATTGAAGAATATCACGGTACTGCGGGGCTATAGTTCTCTGAATAACAGGTATCCGAGCACCTCCGACGGTCCGAATAGAGCTCATTATCCCCGGACCAACCTAAAACTTAGACTGTGGTGAATCTGATCGCTAGGTTCGTGAGACGGAAGGATTTATCTCTTCAAGCTCCTAGTACAGTTACGCATTGTGCGTAGTGGGGAGACAGCGGCCTGGCCCGCCCATGAGAATTCGTAAAATACCCGCCAAGGGCTCCTAGGCCGTGGCTACCTATTCATTTTAGTGAGCGGTTATAGTGAACAACAGCCAAGATGCGGGAATAACACCGCATCAAACATAGCGGTACGGTGCGGCGATCCCATCATACACCGTATACAGAGCCATCGAGCGACCGATCTTGCCGCTTCTTAAGGTATCGTTGGGGCGCACAGTCTACAAAGTAAATGTCTTGTTCCAACGTCTAGTGTAGAAAGGAGTAGGTATTACTGATCAAGCTGTTTAACGATCCCATGATGTAAATGCTCTCGGTTTGAACTGACATTCGAGGCACGGTTTTAAATCTTCCAAAGGGCACCGTGTCTGAGTAGGGTTCGTGTTCAGCCACACCATTCAGCAATTGAGACCTCTGCGAGCATTACCCTCATGCGCATTGACCTAATAAACGCCCCGGGTAAACTTAGTACTCAGGACAGATTAACCCGGCGCGAGCTTGGTTGGCTGTGTGACTGTAGTTCGAACACTTTCGTCACGATAAGATTGCGATAAACGGCTCGCCGACCGTATGGTTAGGTCGGGTTATGTCCTACAGCCCCACTACAAATGAGAGCTGCGTTTAGACTTGAGGTTCCGACCATAATTCTAGATTGGACCTATGAAGCCAAGAAAAGAGCGATCGTCATCGATACTTTGTCCAGTCTGGAGTCGAGACACGCCAGTACCTCGCCTAACGACTTTGTTCAAATAGATGTTACCTGGTGAGTGAGGTCTGCGAGGGGCGTCAATGCTGGCTTGTTCCGATGCAGACATGGCGAACGACTATCGCAGGAGCCAGGCGGGCCCTGGACTTATGAGTGGAGATACATCATGGGGAGGGTAGCGTATTGGGGCCAGCCAGATATCAAATTAGACATTAAGCGCGATCCGGGAATGATCAGTCTGAGTCGGCAATTTCAGGCTGTTCAGACACCGGTACCACAAGTGGATCTTACATCCCCCCACTACTCACGCCCGACGGGAATCCAAATTAGACTGCAAACTTATCGGAATACGTCAGCGTCACCCTAAATCTACGAAGATACTTGTTGAATAACACTAGGGTGCGGCCGCATAAGACGATTGATAGAAATACATACATCTGTCTATAACCAGTGTAACACATTCACTAGAGATACACGGCTCGGCTAGTTACCGTAAAAGCATAATGTAAACGGCGTCGCGTAATTAGAATATACAATGGTGTACGTGTCATACAGATCTCGCCCAAGGTAATCATATCCCTTGCTACTGGGCCCATGTCTGACATGCATCCGCACTGTAGATGTCTATTCCTCAGCCGTGCCATTTCTCCTTACAGGTGACTGGGGCATTTTTGAACGGCCAGGCGTTCTTGGGACGAACTCAGCTGACAAACCAGTGAATTTTATCGCTTCGCCTTCCGAATATAAACATTCCAAATTTTCGCAAAAGACATATATAGGTCCTATAGTTTTAGTGCCGTTTCAGATATAGTGTAGACTATCCCAAATGGACTAGGTTCTTAGCCTGTTGCTAGCACCCCAGTAATTCCTTGAAAAATGCTGTGTACTCGCGACGACTCGTGGGGGACTCACGCCCATAACAGTGATCGCAGTAGTCTCGGATTTTAATCCCTACTGCACGTTTTCGCTGGGTGTGGAATTCACCCTCAGGCTCGGGGAGCTTATTTTCTGGCAAGCGGTAAGCCACAGTGTCATCCCAACGTGCGGGAGCTGGTTGCCTAAAACCTCAGATTTGAGTCCGACAAGGAACAATCTTAGAGTGCATCATAAAGCTACCCTGTTGCTCAAGCCAGCTCATGCAACGTTCATCACATCCAATAGCTCGATACATTTCCGACTTGGGGCTAACGGGCGAACCGGGGGGATCAATCGACACGGGGTCTGCTGGTAAGACAGATCTGGGATCACCGTGTTGAACTCTAGCATCAACTATATGAATCCCAGCACCGCTTAGACAATGCAGCTGCGTGCATGATATAACCCTACAGTAGCCAACTAACTGCGTGGCGTAGCGATGAGCTACACTCAGCTAAGAAAACTTGGTAACGTGTATCGTACTTTTTCTTAACAGCCTTTCCGTCCCAGCTCTGATGGGGCATATTCCCACGCCATGGCCCACTCTCAGCGATCACGAAGCCCCGTGCTAACCTCAATGAAAGATTACACACAAAGATAGGGTGGGAGTAAGTACATGAACCACCACACATAGGCCCGATGATAAATATTAGCACTCTCTTGATGTGATCGAAATCTGAGAACAAATGATTCGAGGTTAGACAGGACGTCTCATTCCTACTGGTTAGCTTGCAATAGAGTGCAGATTGATGTTACGAG";
        Scanner scanner = new Scanner(System.in);
        
        System.out.println("Insert Key: ");
        String in = scanner.nextLine();
        
        String[] rawDividedInput = in.split("[?*]");

        List<String> nonEmptyInput = new ArrayList<>();
        for (String part : rawDividedInput) {
            if (!part.isEmpty()) {
                nonEmptyInput.add(part);
            }
        }

        String[] dividedInput = nonEmptyInput.toArray(new String[0]);
        
        ArrayList<String> splitGenoma = new ArrayList<String>(Arrays.asList(genoma.split(String.format("(?=%1$s)", dividedInput[0]))));
        ArrayList<String> genomaInst = new ArrayList<String>();

        for (int i = 1; i < dividedInput.length; i++) {
            genomaInst = (ArrayList) splitGenoma.clone();
            splitGenoma.clear();
            
            for (int j = 0; j < genomaInst.size(); j++) {
                String key = String.format("(?=%1$s)", dividedInput[i]);
                List<String> newSplitGenoma = Arrays.asList(genomaInst.get(j).split(key));
                if (newSplitGenoma.size() > 1) {
                    
                    splitGenoma.addAll(newSplitGenoma);
                    
                }
                
            }
        }

        String out ="";
        int genomaIndex = 0;
  

        dividedInput = in.split("(?=[?*])|(?<=[?*])");
        splitGenoma.removeIf(n ->(n==""));
        int i = 0;
        while (i < dividedInput.length) {
            if (dividedInput[i].equals("?")) {
                //TODO RETHINK THIS PART
                out += splitGenoma.get(genomaIndex).charAt(0);
            } else if (dividedInput[i].equals("*")) {
                if (i+1 == dividedInput.length) {
                    out += splitGenoma.get(genomaIndex);
                    genomaIndex++;
                } else if (dividedInput[i+1].equals(splitGenoma.get(genomaIndex))) {
                    i++;
                }
            } else if (splitGenoma.get(genomaIndex).equals(dividedInput[i])){
                out += dividedInput[i];
                genomaIndex++;
                i++;
            }
            
        }
        System.out.println("Output: ");
        if (dividedInput.length > 1) System.out.println(out);
        else System.out.println("None");
    }
}